  ain-addBenchMarkPerfMon[m
* [32mmain[m
  main-addAllegroSimTest[m
  main-addAttributionAnalysis[m
  main-addBasicPlotting[m
  main-addBenchMarkPerfMon[m
  main-addCodeCovConfig[m
  main-addCodecovTest[m
  main-addCodecovTests[m
  main-addIDEABenchmarks[m
  main-addInitialDashboard[m
  main-addPerEventTiming[m
  main-addPerRegionTimingPlugin[m
  main-addStepAnalysis[m
  main-dashboardDeployment[m
  main-fixGSwe[m
  main-fixPerRegionAtBirthTiming[m
  main-fixSweepSemantics[m
  main-fixSweepSemantix[m
  main-improveDashboard[m
  main-improveMachineInfo[m
  main-improvePlotting[m
  main-overhaulDashboard[m
  main-overhaulTrendTab[m
  main-regionTimingPlots[m
  main-restructStorage[m
  main-switchToPlotly[m
