apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dd4bench-dashboard
  namespace: dd4bench
  labels:
    app: dd4bench-dashboard
spec:
  host: dd4bench-dashboard.app.cern.ch
  to:
    kind: Service
    name: dd4bench-dashboard
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
