"""Reconcile a ddsim steering file with a patched geometry.

Steering files configure sensitive detectors by subdetector name.  Most of
those mappings tolerate a name that is not in the geometry:
``SIM.action.mapActions`` and ``SIM.filter.mapDetFilter`` are substring-matched
against the sensitive detectors that actually exist, so a stale entry is simply
never matched.  ``SIM.geometry.regexSensitiveDetector`` is the exception — each
key is resolved to a ``DetElement`` by ``Geant4RegexSensitivesConstruction``,
and a missing one aborts ddsim during ``kernel.initialize()`` with::

    dd4hep: DetElement::child Unknown child with name: <detector>

Geometry sweeps remove subdetectors from the compact file, so any steering file
naming a removed subdetector that way would fail.  This module writes a copy of
the steering file with a generated epilogue that drops the unresolvable entries,
and leaves everything else untouched.

The copy is written into the run's log directory next to ``<label>.log`` so the
exact configuration a run used stays inspectable after the fact.

Only patched runs are reconciled.  Baseline runs use the original steering file
verbatim, which keeps a genuine typo in a steering file a hard error rather than
a silently dropped sensitive detector.
"""

from __future__ import annotations

from pathlib import Path

#: ddsim spellings that introduce a steering file path as the *next* argument.
_STEERING_FLAGS = ("--steeringFile", "-S")

#: Spellings carrying the path in the same argument.  ``argparse`` accepts
#: ``--long=value`` and, for short options, a directly appended value.
_STEERING_PREFIXES = ("--steeringFile=", "-S")


#: Appended to the copy. Placeholders are substituted by :func:`_epilogue`;
#: written without f-string escaping so it reads as the code it emits.
_EPILOGUE_TEMPLATE = '''

# ----------------------------------------------------------------------------
# Generated by k4bench for the run "__LABEL__".
#
# Everything above is a verbatim copy of
#   __ORIGINAL__
# That run simulates a compact file with some subdetectors removed. Keys of
# SIM.geometry.regexSensitiveDetector are resolved as DetElements and abort
# ddsim when the subdetector is absent, so unresolvable ones are dropped below.
# ----------------------------------------------------------------------------
_k4bench_present = set(__PRESENT__)
_k4bench_regex_sd = getattr(SIM.geometry, "regexSensitiveDetector", {})
for _k4bench_key in list(_k4bench_regex_sd):
    # Keys may be paths ("Calo/layer"); only the leading element is a subdetector.
    if _k4bench_key.strip("/").split("/")[0] not in _k4bench_present:
        del _k4bench_regex_sd[_k4bench_key]
        print("k4bench: dropped regexSensitiveDetector[%r], not in this geometry"
              % _k4bench_key)
'''


def _epilogue(original: Path, label: str, present_detectors: set[str]) -> str:
    """Return steering-file code dropping regex SDs absent from the geometry."""
    return (
        _EPILOGUE_TEMPLATE
        .replace("__ORIGINAL__", str(original))
        .replace("__LABEL__", label)
        .replace("__PRESENT__", repr(sorted(present_detectors)))
    )


def _find_steering(args: list[str]) -> tuple[int, str, str] | None:
    """Locate the steering file in *args*.

    Returns ``(index, prefix, path)``, where replacing ``args[index]`` with
    ``prefix + new_path`` preserves the spelling the caller used, or None when
    *args* carries no steering file.
    """
    for i, arg in enumerate(args):
        if arg in _STEERING_FLAGS:
            # Path is the next argument; a trailing flag with no value is left
            # alone so ddsim reports it, rather than duplicating its message.
            if i + 1 < len(args):
                return i + 1, "", args[i + 1]
            return None
        for prefix in _STEERING_PREFIXES:
            if arg.startswith(prefix) and len(arg) > len(prefix):
                return i, prefix, arg[len(prefix):]
    return None


def reconcile_steering_file(
    *,
    extra_args: list[str],
    present_detectors: set[str],
    log_dir: Path,
    label: str,
) -> list[str]:
    """Return *extra_args* with ``--steeringFile`` pointing at a reconciled copy.

    Returns *extra_args* unchanged when it carries no steering file, so callers
    can apply this to every patched run unconditionally.

    Parameters
    ----------
    extra_args:
        ddsim arguments for this run, as passed through to the executor.
    present_detectors:
        Subdetector names present in the patched geometry for this run.
    log_dir:
        Directory the reconciled copy is written to.
    label:
        Run label; used as the filename stem.

    Returns
    -------
    list[str]
        Arguments to hand to :func:`k4bench.runner.executor.run_ddsim`.
    """
    found = _find_steering(extra_args)
    if found is None:
        return extra_args
    idx, prefix, path = found

    original = Path(path)
    dest = log_dir / f"{label}_steering.py"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        original.read_text() + _epilogue(original, label, present_detectors)
    )

    patched = list(extra_args)
    patched[idx] = f"{prefix}{dest}"
    return patched
